Declare ML Module "coq-completion.plugin".

(*
This example was automatically generated by converting from
klein.trs: 

(VAR x y)
(RULES
f(x) -> f(y)
f(y) -> b
)

*)

Require Import Coq.Setoids.Setoid.

Parameter G : Set.
    
Parameter b : G.
Parameter f : G -> G.
Axiom ax0 : forall y, f y = b.
Axiom ax1 : forall x y, f x = f y.
Create HintDb hint_compl.
Complete ax0 ax1 : b f : hint_compl.
