#!/bin/bash

TIMEOUT=20

# テーブルのヘッダーを出力
echo "# Examples"
echo ""
echo "Examples in this directory are auto-generated by converting examples in Toma repository."
echo ""
echo "Each example is tested with a timeout of $TIMEOUT seconds."
echo "- 🟢 OK: Compilation completed successfully."
echo "- 🔴 FAIL: Runtime error or timeout."
echo ""
echo "## Results"
echo ""
echo "|file|status|"
echo "|---|---|"

# 現在のディレクトリから再帰的に.vファイルを検索して処理
find . -name '*.v' | while read -r file; do
    if timeout $TIMEOUT coqc "$file" > /dev/null 2>&1; then
        echo "| [$file]($file) | 🟢 OK |"
    else
        echo "| [$file]($file) | 🔴 FAIL |"
    fi
done
